# Generated by Django 5.2.2 on 2025-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_user_email_remove_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailorphone',
            field=models.EmailField(max_length=65, null=True, unique=True),
        ),
    ]
